/* mbed Microcontroller Library
 * Copyright (c) 2006-2013 ARM Limited
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */  

#ifndef __GATT_SERVER_H__
#define __GATT_SERVER_H__

#include "blecommon.h"
#include "UUID.h"
#include "GattService.h"
#include "mbed.h"

/**************************************************************************/
/*!
    \brief
    The base class used to abstract GATT Server functionality to a specific
    radio transceiver, SOC or BLE Stack.
*/
/**************************************************************************/
class GattServer
{
    protected:
        FunctionPointer m_callback_event;

    public:
        /******************************************************************/
        /*!
            \brief
            Identifies GATT events generated by the radio HW when an event
            callback occurs
        */
        /******************************************************************/
        typedef enum gatt_event_e
        {
          GATT_EVENT_TODO     = 0x01 /**< ... */
        } gattEvent_t;

        /* These functions must be defined in the sub-class */
        virtual ble_error_t addService(GattService &) = 0;
        virtual ble_error_t readValue(uint8_t, uint8_t[], uint16_t) = 0;
        virtual ble_error_t updateValue(uint8_t, uint8_t[], uint16_t) = 0;

        uint8_t serviceCount;
        uint8_t characteristicCount;

        /* Event callback */
        void attach(void (*function)(void)) { 
            m_callback_event.attach( function );
        }
 
        template<typename T>
        void attach(T *object, void (T::*member)(void)) {
            m_callback_event.attach( object, member );
        }
};

#endif
